### ISSUE TITLE
[Request] Please put on CF

### ISSUE THREAD

**Issue by gamerpotion** [Wesley1808/AdvancedChat#3]
Hi, am already using servercore on DarkRPG, so was wondering if you will be putting this mod on CurseForge so can officially bundle it with the modpack, 
thanks

**Comment by Wesley1808** [comment]
I was planning on putting this mod on CurseForge aswell - and should've done so a while back, but kinda forgot about it.
I will be doing that now 👍 (when it gets accepted anyway)

**Comment by Wesley1808** [comment]
Looks like it got approved now
https://legacy.curseforge.com/minecraft/mc-mods/advanced-chat
