### ISSUE TITLE
Mute command

### ISSUE THREAD

**Issue by DonorKrovi** [Wesley1808/AdvancedChat#7]
For this plugin, this is what you need!! It's also a pity that the filter for curses is quite easy to bypass, which is why this team is suitable for violent players

**Comment by Wesley1808** [comment]
You can use [BanHammer](https://github.com/Patbox/BanHammer) to handle punishments, including but not limited to mutes and tempmutes.

And yeah word filters aren't that simple (make them too aggressive and they will false flag way too easily), but you might be able to find some regular expressions (regex) on the internet for common words you want to block, as it supports those aswell.

Or alternatively, make your own regular expressions - but they are a bit difficult to understand.

**Comment by DonorKrovi** [comment]
> You can use [BanHammer](https://github.com/Patbox/BanHammer) to handle punishments, including but not limited to mutes and tempmutes.
> 
> And yeah word filters aren't that simple (make them too aggressive and they will false flag way too easily), but you might be able to find some regular expressions (regex) on the internet for common words you want to block, as it supports those aswell.
> 
> Or alternatively, make your own regular expressions - but they are a bit difficult to understand.

Many thanks!
